### ISSUE TITLE
亮度调节失效Bug

### ISSUE THREAD

**Issue by Fyg369** [uwu-gl/OOS_kernel_oneplus_sdm845#3]
我测试了一加6T很多第三方内核，都会有一个问题就是手指不停的快速锁屏解屏，会出现屏幕亮度变暗且亮度调节失效，偶尔也会突然屏幕变暗亮度调节失效，顺便问下这个内核源码是否能在Actions编译出来？

**Comment by uwu-gl** [comment]
在action里编译是可以的
另外，你遇到了触屏问题吗（触屏根本不能用的情况）

**Comment by Fyg369** [comment]
> 在action里编译是可以的 另外，你遇到了触屏问题吗（触屏根本不能用的情况）

我还没开始测试这个内核，我用了其它第三方内核会出现屏幕变暗，亮度调节失效的问题。

**Comment by Fyg369** [comment]
在action里编译出错

![Screenshot_20240511-224238](https://github.com/uwu-gl/OOS_kernel_oneplus_sdm845/assets/142138034/98be2c3f-cc43-4a0b-a247-3efa8ac6d416)

**Comment by Fyj69** [comment]
这里的链接作者已经删库跑路了
![6](https://github.com/uwu-gl/OOS_kernel_oneplus_sdm845/assets/18164452/8d262479-334c-432e-9919-aef3fc2bc7a6)

**Comment by uwu-gl** [comment]
他并没有删库吧。。。
另外，请你去看看新的链接哦

**Comment by uwu-gl** [comment]
原仓库中给出了当前的链接，完全可以使用action编译。（我才不会告诉你我还没集成ksu呢）

**Comment by Fyg369** [comment]
> 原仓库中给出了当前的链接，可以完全使用action编译。~（我才不会告诉你我还没有集成ksu呢）~

可以不用集成那么麻烦，有现成的ksu补丁比集成比较方便，另外对于触屏问题我还没刷入内核体验不到这个BUG

**Comment by uwu-gl** [comment]
> > 原仓库中给出了当前的链接，可以完全使用action编译。~（我才不会告诉你我还没有集成ksu呢）~
> 
> 可以不用集成那么麻烦，有现成的ksu补丁比集成方便太多了，另外对于触屏问题我还没刷入内核体验不到这个BUG，另外再请问下你给的最新仓库链接不需要DTC了吗？

没错哒，不需要外挂dtc咯
另外，我也在考虑不把ksu当作submodule看，太坑了
如果你想继续讨论，请在新仓库重新打开issue，这个仓库说不定我什么时候就删了呢

**Comment by Fyj69** [comment]
> > > 原仓库中给出了当前的链接，可以完全使用action编译。~（我才不会告诉你我还没有集成ksu呢）~
> > 
> > 
> > 可以不用集成那么麻烦，有现成的ksu补丁比集成方便太多了，另外对于触屏问题我还没刷入内核体验不到这个BUG，另外再请问下你给的最新仓库链接不需要DTC了吗？
> 
> 没错哒，不需要外挂dtc咯 另外，我也在考虑不把ksu当作submodule看，太坑了 如果你想继续讨论，请在新仓库重新打开issue，这个仓库说不定我什么时候就删了呢

问下触屏问题解决了吗？我想把ksu和lxc还有Kali nethunter补丁全部打上，这些补丁除了lxc其它补丁都不用集成，顺便把zstd升级一下

**Comment by uwu-gl** [comment]
> > > > 原仓库中给出了当前的链接，可以完全使用action编译。~（我才不会告诉你我还没有集成ksu呢）~
> > > 
> > > 
> > > 可以不用集成那么麻烦，有现成的ksu补丁比集成方便太多了，另外对于触屏问题我还没刷入内核体验不到这个BUG，另外再请问下你给的最新仓库链接不需要DTC了吗？
> > 
> > 
> > 没错哒，不需要外挂dtc咯 另外，我也在考虑不把ksu当作submodule看，太坑了 如果你想继续讨论，请在新仓库重新打开issue，这个仓库说不定我什么时候就删了呢
> 
> OK，问下触屏问题解决了吗？我想把ksu和lxc还有Kali nethunter补丁全部打上，这些补丁除了lxc其它补丁都不用集成，顺便把zstd升级一下

触屏问题解决了，放心刷
ksu我刚打完，lxc我这个周或者下个周做，zstd为什么要升级呢？

**Comment by uwu-gl** [comment]
请留意您的酷安私信
